server:
  port: 5000
  error:
    include-message: always
existingApis:
  url: "localhost:3001"
  paths:
    get-product-similarids: "/product/{productId}/similarids"
    get-product-productId: "/product/{productId}"